# schema/datatypes and columns you can get from experiment notebook. 

# in ML, if you are working on tabular data, always create schema.yaml. We will use this file in  data validation 

COLUMNS:
  fixed acidity: float64
  volatile acidity: float64
  citric acid: float64
  residual sugar: float64
  chlorides: float64
  free sulfur dioxide: float64
  total sulfur dioxide: float64
  density: float64
  pH: float64
  sulphates: float64
  alcohol: float64
  quality: int64


TARGET_COLUMN:
  name: quality
  