artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion  #download the data from url, and store in artifact/data_ingestion folder instead storing it in main folder wine.zip and unzip
  source_URL: https://github.com/shalmali30/EndToEndMachineLearningProject/raw/main/winequality-data.zip  
  local_data_file: artifacts/data_ingestion/data.zip  #data.zip will the name of the downloaded file 
  unzip_dir: artifacts/data_ingestion


data_validation:
  root_dir: artifacts/data_validation
  unzip_data_dir: artifacts/data_ingestion/winequality-red.csv
  STATUS_FILE: artifacts/data_validation/status.txt  #if all the columns are availble in the schema, in status.txt file it will return True.

data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/winequality-red.csv

model_trainer:
  root_dir: artifacts/model_trainer
  train_data_path: artifacts/data_transformation/train.csv
  test_data_path: artifacts/data_transformation/test.csv
  model_name: model.joblib   # either use joblib or pickle

#joblib is particularly useful when dealing with large NumPy arrays

model_evaluation:
  root_dir: artifacts/model_evaluation
  test_data_path: artifacts/data_transformation/test.csv  #for evaluation we give test data and not the train data
  model_path: artifacts/model_trainer/model.joblib  # Model path 
  metric_file_name: artifacts/model_evaluation/metrics.json # onve the evaluation is performed we have to save it. We are saving it in JSON format inside evaluation folder